
package mesaayudatec;

import dao.LoginDAO.UserInfo;
import mesaayudatec.newpackage.model.MySqlConexion;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;


public class TablaUsuario extends javax.swing.JFrame {

  private final UserInfo usuario;

    // -------- CONSTRUCTOR PRINCIPAL ----------
    public TablaUsuario(UserInfo usuario) {
        this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(null);
        cargarDatosUsuario();
        cargarIncidencias();
    }

    // Evita uso sin login
    private TablaUsuario() {
        throw new UnsupportedOperationException("No se puede usar sin login.");
    }

    // -------- REFRESCAR DATOS ----------
    public void refrescar() {
        cargarDatosUsuario();
        cargarIncidencias();
    }

    // -------- CARGAR DATOS DEL USUARIO ----------
    private void cargarDatosUsuario() {
        jT_Nombre.setText(usuario.nombre);
        jT_Tipo_de_usuario.setText(usuario.rol);
        jT_Departamento.setText(String.valueOf(usuario.idDepartamento));
    }

    // -------- CARGAR INCIDENCIAS ----------
    private void cargarIncidencias() {
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "Título", "Registro", "Departamento", "Encargado", "Tiempo", "Estatus", "Prioridad"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // todas las celdas no editables
            }
        };
        jTable_Usuario.setModel(model);

        // Ocultar columna ID
        jTable_Usuario.getColumnModel().getColumn(0).setMinWidth(0);
        jTable_Usuario.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable_Usuario.getColumnModel().getColumn(0).setWidth(0);

        String sql = """
            SELECT 
                t.id,
                t.titulo,
                t.registrado AS fecha_registro,
                d.nombre AS departamento,
                u.nombre AS encargado,
                TIMESTAMPDIFF(MINUTE, t.registrado, NOW()) AS tiempo,
                e.nombre AS estatus,
                p.nombre AS prioridad
            FROM tb_ticket t
            JOIN tb_departamento d ON d.id = t.id_departamento
            JOIN tb_usuario u ON u.idusuario = t.id_usuario
            JOIN tb_estados e ON e.id = t.id_status
            JOIN tb_prioridades p ON p.id = t.id_prioridad
            WHERE t.id_usuario = ?
        """;

        try (Connection con = new MySqlConexion().getConexion();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, usuario.idUsuario);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    model.addRow(new Object[]{
                            rs.getInt("id"),
                            rs.getString("titulo"),
                            rs.getTimestamp("fecha_registro"),
                            rs.getString("departamento"),
                            rs.getString("encargado"),
                            rs.getInt("tiempo") + " min",
                            rs.getString("estatus"),
                            rs.getString("prioridad")
                    });
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar incidencias: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // -------- ABRIR DETALLE DE INCIDENCIA ----------
    private void abrirDetalle() {
        int filaSeleccionada = jTable_Usuario.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "⚠️ Selecciona un ticket para ver su detalle.");
            return;
        }

        // Obtener el ID del ticket seleccionado
        int idTicket = Integer.parseInt(jTable_Usuario.getValueAt(filaSeleccionada, 0).toString());

        // Abrir ventana DetalleIncidencia
        DetalleIncidencia detalle = new DetalleIncidencia(usuario.idUsuario, idTicket, this);
        detalle.setVisible(true);
        this.setVisible(false);
    }

    // -------- ABRIR REGISTRO ----------
    private void abrirRegistro() {
        Registro reg = new Registro(usuario.idUsuario, this);
        reg.setVisible(true);
        this.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Usuario = new javax.swing.JTable();
        jT_Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jT_Departamento = new javax.swing.JTextField();
        jT_Tipo_de_usuario = new javax.swing.JTextField();
        jB_Registro = new javax.swing.JButton();
        jB_SeguimientoActio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jTable_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Usuario);

        jT_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NombreActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jB_Registro.setBackground(new java.awt.Color(51, 51, 51));
        jB_Registro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jB_Registro.setForeground(new java.awt.Color(255, 255, 255));
        jB_Registro.setText("Registro");
        jB_Registro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jB_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RegistroActionPerformed(evt);
            }
        });

        jB_SeguimientoActio.setBackground(new java.awt.Color(51, 51, 51));
        jB_SeguimientoActio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jB_SeguimientoActio.setForeground(new java.awt.Color(255, 255, 255));
        jB_SeguimientoActio.setText("Seguimiento");
        jB_SeguimientoActio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jB_SeguimientoActio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SeguimientoActioActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tabla Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(296, 296, 296))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Tipo_de_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jB_SeguimientoActio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jB_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_SeguimientoActio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jT_Tipo_de_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_SeguimientoActioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SeguimientoActioActionPerformed
 abrirDetalle();

    }//GEN-LAST:event_jB_SeguimientoActioActionPerformed

    private void jB_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RegistroActionPerformed
 Registro reg = new Registro(usuario.idUsuario, this);
    reg.setVisible(true);
    this.setVisible(false); // ocultamo
    }//GEN-LAST:event_jB_RegistroActionPerformed

    private void jT_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Registro;
    private javax.swing.JButton jB_SeguimientoActio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_Departamento;
    private javax.swing.JTextField jT_Nombre;
    private javax.swing.JTextField jT_Tipo_de_usuario;
    private javax.swing.JTable jTable_Usuario;
    // End of variables declaration//GEN-END:variables

    
}
